### ISSUE TITLE
No permission dialog for camera and microphone 

### ISSUE THREAD

**Issue by cupidleomanoj** [opentok/cordova-plugin-opentok#141]
**Hello, I need to create live video streaming, I am using OutSystem for development, when loaded this plugin in InAppBrowser, it does not ask for Camera and Microphone permissions. But the same works fine in web browser.

**Comment by msach22** [comment]
@cupidleomanoj Hmm, it looks like the InAppBrowser can't access the Cordova APIs which is what this plugin uses. I'm not sure if this plugin is compatible with InAppBrowser, you can try to use the OpenTok JS SDK with the InAppBrowser and it may work for Android, but not iOS since it doesn't support WebRTC.
