### ISSUE TITLE
Multiple Access Origins

### ISSUE THREAD

**Issue by gameFace22** [opentok/cordova-plugin-opentok#40]
Hi, 

We are using cordova-plugin-opentok in one of our projects. And we have an requirement to set the access origin to only *.example.com. 
But, while building the application, access-origin is also set to * (there are 2 access origins in our's application's config.xml) 
We are assuming it is caused by the opentok plugin from [here](https://github.com/songz/cordova-plugin-opentok/blob/master/plugin.xml)

Can you please let know if there is a workaround to only set the access origin to *.example.com and still be able to use the opentok plugin without any issues?

Thank you!

**Comment by mark-veenstra** [comment]
@msach22: I think it is possible to remove the line `<access origin="*" />` from `plugin.xml`, because of the following reasons:
- At the moment it is only added to the platform ios, so android also does not have this access origin
- According to the [docs](https://cordova.apache.org/docs/en/latest/guide/appdev/whitelist/) the default is allow all origins. So leaving it out does the same.
- If we would like to add the access origins, we need to only include the servers that are needed. And this setting is equal to all platforms, like: `<access origin="https://*.tokbox.com" />` and `<access origin="https://*.opentok.com" />` and `<access origin="wss://*.tokbox.com" />`

@gameFace22: I do think that adding the TokBox servers to the control list is necessary to be able to use video calling. If you only allow access to and from `*.example.com` will disallow your app to connect to the TokBox servers. So within your `config.xml` you still need to add the TokBox servers. If I am correct it would be: `<access origin="https://*.tokbox.com" />` and `<access origin="https://*.opentok.com" />` and `<access origin="wss://*.tokbox.com" />`.

Also the CSP within the `index.html` need these servers.

**Comment by gameFace22** [comment]
@mark-veenstra Thank you so much for clarifying. 

Currently, I can see that the [plugin.xml](https://github.com/songz/cordova-plugin-opentok/blob/master/plugin.xml) has ```<access origin>``` set to ```*```
Should that be replaced with ```<access origin="https://*.tokbox.com" />``` and ```<access origin="https://*.opentok.com" />``` and ```<access origin="wss://*.tokbox.com" />```

Would be more than happy to open a PR 😄

**Comment by mark-veenstra** [comment]
@gameFace22 I think best for now is to remove the access origin from the plugin.xml, since it is also not set for Android. You can remove it and test what happens.

**Comment by gameFace22** [comment]
Awesome. 
Thank you. Will update you in case something breaks.

**Comment by gameFace22** [comment]
Awesome. Thank you!
