### ISSUE TITLE
Testing branch 3.2.0 gives black screen on android 6.0.0. 

### ISSUE THREAD

**Issue by primashah** [opentok/cordova-plugin-opentok#46]
I noticed lots of PRs were merged on this branch and was trying to test it on our existing ionic app. The app launches fine but ends up with black screen. Dont see any console errors. For me looks like a css issue but our app works fine with this plugin repo from master branch.

**Comment by mark-veenstra** [comment]
Do you apply z-index on publishers or subscribers? If so the cams are behind the webview as described here: https://github.com/opentok/cordova-plugin-opentok/blob/3.2.0/docs/README.md#positioning-the-cameras-behind-or-before-webview

**Comment by primashah** [comment]
I dont have publisher / subscribers on home page. The ioinic view/page which has publisher and subscriber is not initialized.  A button navigates from home view to call view and the call view page initiates a call and hence the opentok session.

**Comment by mark-veenstra** [comment]
I think I understand it. When you start your app the homepage is black. This is because of a issue with the scrolling on Android. In this PR: https://github.com/opentok/cordova-plugin-opentok/blob/3.2.0/docs/README.md#positioning-the-cameras-behind-or-before-webview

We are working on a solution on this with a different scrolling mechnism. Therefore 3.2.0 is not yet released. If you would like to test it give the HTML body a fixed height in pixels.

Do not use 3.2.0 in production yet. As I said a solution will follow.

**Comment by primashah** [comment]
ok I will give it a try. Any idea when 3.2.0 will be ready to use?

**Comment by msach22** [comment]
@primashah @mark-veenstra and his team are working on some PRs so we will release 3.2.0 as soon as we have the scrolling fixed

**Comment by msach22** [comment]
@primashah are you still seeing the black screen?

**Comment by mark-veenstra** [comment]
Otherwise you can test [this branch](https://github.com/Mediapioniers/cordova-plugin-opentok/tree/all-fixes), it contains a different scrolling solution and removes the black screen issue (and other scrolling issues).
Do not use it in production since it will be deleted as soon as it is merged into the main branch/repository.

**Comment by ph-shah** [comment]
@mark-veenstra : I will test it some time and let you know. 
@msach22 havent got chance to test again after creating this issue. As @mark-veenstra  is suggesting, I will try to test on the branch he recommends and post my observations here.

**Comment by msach22** [comment]
@ph-shah thanks for letting me know!

**Comment by msach22** [comment]
We tested 3.2.0 out and there were no issues. Please re-open and provide logs if issue persists
